trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20'
  displayName: 'Install Node.js'



- task: CopyFiles@2
  inputs:
    contents: '**/*.json'
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)
    artifact: package
  displayName: 'Publish artifacts'


