trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm pack
  displayName: 'npm install and build'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.tgz'
    destinationFolder: 'mypackage'
    cleanDestinationFolder: true
    overwriteExistingFiles: false
  displayName: 'Extract .tgz file'

- task: CopyFiles@2
  inputs:
    contents: 'mypackage/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)
    artifact: package
  displayName: 'Publish artifacts'

- script: |
    cd $(Build.ArtifactStagingDirectory)/mypackage
    ls
  displayName: 'Find the files'
