trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  inputs:
    contents: '**/*.json'
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)
    artifact: package
  displayName: 'Publish artifacts'
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'e367a5ec-9b68-474f-b8df-f8f83a0eb5d2/2a5636a2-bab9-4ed6-8e8d-be882ec10308'
    versionOption: 'patch'